### ISSUE TITLE
checksum-tools no longer works on remote files

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/checksum-tools#6]
As of yesterday afternoon, trying to run checksum-tools on some remote files returns the following error:

```
$ checksum-tools -a verify -e .md5 -r smpl@sul-smpl.stanford.edu:/pool0/smpl17/Noh_Theater/content/vp161wb6699 -s /usr/bin/openssl
Password:  
/Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/lib/checksum-tools/remote.rb:24:in `initialize': undefined method `[]=' for false:FalseClass (NoMethodError)
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:20:in `new'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:20:in `new'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/bin/checksum-tools:166:in `<top (required)>'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/checksum-tools:23:in `load'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/checksum-tools:23:in `<main>'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```
Michael A. has reported the same behavior.

**Comment by hannahfrost** [comment]
I would bet that some recent patching has caused the issue.

**Comment by jcoyne** [comment]
It looks as though you are passing a path to the `-r` flag, but according to the documentation, the `-r` is for "recurse into subdirectories" and it doesn't take any argument.

Does it work if you do this?
```
checksum-tools -a verify -e .md5 -r -s /usr/bin/openssl smpl@sul-smpl.stanford.edu:/pool0/smpl17/Noh_Theater/content/vp161wb6699
```

**Comment by jcoyne** [comment]
I'm also interested if you could post the contents of your `~/.checksum-tools-system` file.

**Comment by oceanofsound** [comment]
`$ checksum-tools -a verify -e .md5 -r -s /usr/bin/openssl smpl@sul-smpl.stanford.edu:/pool0/smpl17/ARS0083_opera
Password:  
/Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/lib/checksum-tools/remote.rb:24:in `initialize': undefined method `[]=' for false:FalseClass (NoMethodError)
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:20:in `new'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/lib/checksum-tools.rb:20:in `new'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/gems/checksum-tools-1.2.0/bin/checksum-tools:166:in `<top (required)>'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/checksum-tools:23:in `load'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/checksum-tools:23:in `<main>'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gwillard/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'`

Hmm, can't find that that `.checksum-tools-system` file in that location. Would it be anywhere else?

**Comment by jcoyne** [comment]
Ah-ha! it looks like that file is supposed to be on the server.  On the server, that file has been zeroed out right at the time the problem started:

```
ls -la /home/smpl/.checksum-tools-system
-rw-r--r-- 1 smpl smpl 0 Mar 20 09:00 /home/smpl/.checksum-tools-system
```
unfortunately I don't know what that should contain.

**Comment by jcoyne** [comment]
I added the following to /home/smpl/.checksum-tools-system and Geoff confirmed it fixed it:
```yaml
openssl: /usr/bin/openssl
```
